### ISSUE TITLE
cannot actually apply the calibration on old python-evdev versions that satisfy pip dependencies

### ISSUE THREAD

**Issue by nonchip** [Virusmater/evdev-joystick-calibration#2]
```
$ sudo evdev-joystick-calibration
Available devices:
2 Logitech Logitech Extreme 3D
Pick one device for the calibration: 2
Move sticks and triggers of Logitech Logitech Extreme 3D to max and min positions.
Press any button to apply.
Configuration for Logitech Logitech Extreme 3D
analog: ABS_X  min:0 max:1023
Traceback (most recent call last):
  File "/usr/bin/evdev-joystick-calibration", line 33, in <module>
    sys.exit(load_entry_point('evdev-joystick-calibration==0.1', 'console_scripts', 'evdev-joystick-calibration')())
  File "/usr/lib/python3.9/site-packages/evdev_joystick_calibration/__main__.py", line 65, in main
    configuration.apply(device, min_max)
  File "/usr/lib/python3.9/site-packages/evdev_joystick_calibration/configuration.py", line 31, in apply
    dev.set_absinfo(int(conf_code), min=conf[conf_code].minimum, max=conf[conf_code].maximum)
AttributeError: 'InputDevice' object has no attribute 'set_absinfo'
```

probably since that's only in `python-evdev` since version 1.3.0 while you don't depend on any specific version.
manually upgrading with `pip install -U evdev` did the trick, you might wanna update your dependencies

**Comment by Virusmater** [comment]
Thx for heads up, updated the dependencies
